### ISSUE TITLE
Method to issue transferable document using Metamask provider from web applicaion

### ISSUE THREAD

**Issue by x-ajnashp** [Open-Attestation/token-registry#10]
Hi,
We are trying to integrate the **"Trade Trust: Issuing Transferable Record"**  feature to our web-based application. So that the users can use the platform and issue the document in trade trust. We are using the `Metamask` provider instead of using their private key to perform an action.

Currently, we are not able to identify a method to do the **issuing the document to blockchain**  action.

Please help to find the method equivalent to the below cli command:

```cmd
open-attestation token-registry issue -a 0x8431012Bc040942B59e3C5bf428221eab0b2f723 --tokenId 0x0d9839a8034cb783d98bd57bcbaafb4dc3614c4193d2edf8a655c1ec6635b7ea --to 0xec733A8322f8216eaf8e5566e750bfee3974B7f3 -n ropsten -f key.txt
```

Thanks in advance.

**Comment by Nebulis** [comment]
You are looking for a way to do it programmatically right ? Here is how we issue => https://github.com/Open-Attestation/open-attestation-cli/blob/master/src/implementations/token-registry/issue.ts#L37

You need to provide the correct metamask signer.

**Comment by x-ajnashp** [comment]
@Nebulis Thanks for the help. But now getting an error saying 
```pre
TypeError: connectedErc721.safeMint(tockenRegestryAddress, uint256) is not a function
``` 
I tried the same as in the CLI issue method.

**Comment by Nebulis** [comment]
We are using `erc721["safeMint(address,uint256)"]` and not `erc721.safeMint`. There is a difference because safeMint is an overloaded function, if you use `erc721.safeMint` you need to provide a 3rd parameter which can be an empty object iirc (`{}`).

If you are still not able to have it working, please share your code.

**Comment by x-ajnashp** [comment]
I used as you mentioned only. Please  find my code below:

```code
const connectedErc721 = await TradeTrustErc721Factory.connect(tokenRegestryAddress, signer);
const issueData = await connectedErc721["safeMint(tokenRegestryAddress, uint256)"](escrowTitleInstanceAddress, documentMerkleRoot, {});
```

``signer`` is created using the Metamask provider.

**Comment by Nebulis** [comment]
Could you create a repo that reproduce the issue? With only this 2 lines it will be hard to help you further

**Comment by x-ajnashp** [comment]
Please find the sample repo link.

https://github.com/x-ajnashp/tt-sample-reppo

**Comment by Nebulis** [comment]
I see that you used `safeMint(this.formData.tokenRegistryAddress, uint256)` but you must use `safeMint(address,uint256)` strictly without any change:
- `safeMint(address,uint256)` is the function name
- `connectedErc21["safeMint(address,uint256)"]` will call the function `safeMint(address,uint256)`. You need to use the square brackets notation instead of the usual dot notation (foo.bar()) because there are specific chars in the function name.

Also you need to add 0x in from of `this.wrappedDocument.signature.merkleRoot` when calling safe mint

**Comment by x-ajnashp** [comment]
Thank you @Nebulis for the help. It worked with the change you mentioned. I was able to create the hash for issuing the document.

But now I am facing one issue while validating the document using https://dev.tradetrust.io/. It showing "**Document not issued**" error.

I have updated the sample repo with the corresponding changes you mentioned above. Could you please check why the error showing?

FYI:
The document issue working and showing valid in the following scenario-

I generated the
- Wrapped document
- escrowTitleInstance

using the sample application and used the CLI option for issuing the document.

**Comment by Nebulis** [comment]
Can you send me an example of a generated doc that faces the error ?

**Comment by x-ajnashp** [comment]
Please find the attached pdf.

[wrapedDocument.pdf](https://github.com/Open-Attestation/token-registry/files/5149199/wrapedDocument.pdf)

**Comment by Nebulis** [comment]
I can see many failed transactions => https://ropsten.etherscan.io/address/0x516e0eaa56e1f2E9906dB6196A8E5d53b5f8de2A

Are you sure it worked correctly for the one you shared ?

**Comment by x-ajnashp** [comment]
Getting the below error while issuing the document.

![image](https://user-images.githubusercontent.com/41932668/91704050-a9459280-ebad-11ea-8f09-da2650fff386.png)


any possible reasons?

I used the same account for creating the token registry, DNS, and in metamask for the signer.

**Comment by Nebulis** [comment]
I'm not sure, I tried your repo with the updates I told you to do (you didn't push) and it's working well.

Try to push the changes you made ? Maybe you are missing some eth in your account ? (I didnt check)

**Comment by x-ajnashp** [comment]
Sorry about that. I updated the changes now. 

The account current balance is 2.9 ETH in Ropsten Test Network.

**Comment by Nebulis** [comment]
Do you always test with the same merkle root ? https://github.com/x-ajnashp/tt-sample-reppo/blob/master/src/app/app.component.ts#L103

The first one will work but subsequent will fail

**Comment by x-ajnashp** [comment]
No. I was testing one other case using hardcoded Merkle root and forgot to revert while pushing the changes.

I have updated the code.

**Comment by Nebulis** [comment]
Ropsten is taking forever to run the tx but as is I don't see anything wrong with your code. I will wait for the tx to complete.

**Comment by Nebulis** [comment]
I'm not sure why but safeMint is indeed always failing however if I ran again the transaction from your app (comment deploy title escrow, set title escrow address and merkle root from the previous failed transaction) then it works:
- https://ropsten.etherscan.io/tx/0x3ffb05e12bfb2531dac0f5c6a7452c6579b86ba138786e6c7a471ba08063a8c4
- https://ropsten.etherscan.io/tx/0x754043017139d5b8dbe43581a7d217f14cba37722bdf629daa1b0a9999ca8d82

The only difference I can spot is the gas limit (159,103 vs 192,540). As is I dont see any reason of this to fail, maybe there is something specific related to metamask happening ?

**Comment by x-ajnashp** [comment]
I tried the same in rinkeby test network but still failing in the last step. :(

![image](https://user-images.githubusercontent.com/41932668/91838904-cc8d4200-ec80-11ea-9f83-b5cc8b982171.png)

**Comment by x-ajnashp** [comment]
Thank you for helping out. I added one temporary solution to execute the issue method again. Now able to validate the document successfully with this temporary fix.
