### ISSUE TITLE
Document surrender flow

### ISSUE THREAD

**Issue by x-ajnashp** [Open-Attestation/token-registry#13]
Hi,

I am trying to implement a UI for Transferable document title transfer using Metamask. Could you please help me on the below queries?

1. Which method to call for the "surrender document" option.
2. How to identify already "Surrendered" documents?

Thanks in advance.

**Comment by rjchow** [comment]
This is subject to further changes are we are still working it out, but currently to surrender a token simply send it to the token-registry such that .ownerOf(tokenId) returns the token registry address

**Comment by x-ajnashp** [comment]
Hi @rjchow, I am trying to implement the latest surrender flow. Can you please help me with the below query?

1. How we can identify the wallet ID  of the issuer using the .tt file?

**Comment by x-ajnashp** [comment]
@rjchow I have implemented the surrender flow. However, facing an issue after the "Accept document surrender" action. Can you please help with this issue?

I have attached the error screenshot and the code I used to do surrender : 

```code 
const tokenReg = openAttest.getData(document).issuers[0].tokenRegistry;
const tokenId = '0x' + document.signature.targetHash;
......

const titleEscrowConnection = await TradeTrustErc721Factory.connect(tokenReg, signer);
const ownerAddress = await titleEscrowConnection.ownerOf(tokenId);
if(ownerAddress === tokenReg) { //  Surrender to issuer 
    currentMetaMaskAddressIsIssuer = await titleEscrowConnection.isMinter(currentMetaMaskAccount); // Show Accept surrender option
}

// Accept document surrender
const destroyToken = await titleEscrowConnection.destroyToken(tokenId);

```

![Error-1](https://user-images.githubusercontent.com/41932668/96082736-60903180-0eee-11eb-8ef0-f3b5a5234d8e.PNG)

**Comment by x-ajnashp** [comment]
Hi @rjchow  I have checked the transaction in https://rinkeby.etherscan.io/ and I can see that the document is transferred to '0x0000000000000000000000000000000000000000' instead of '0x000000000000000000000000000000000000dEaD'.
Please find the transaction Ids below:

1. 0xa5417cf2dea4e0b9b8631dbab7ffa7364bfe5a2be06be3998247f9e1c3a273ce
2. 0xfe87bf00b2f5316f1bca92e8d44acb0f3fde6af15c1ff3960bf4d3fc2efc50c7

I am using @govtechsg/token-registry": "2.4.0"

**Comment by justussoh** [comment]
Hi @x-ajnashp, even though your web application may be on `@govtechsg/token-registry": "2.4.0"`, the token registry from which the document is issued from may not be updated. I would recommend, deploying a new token registry@^2.3.0 and [verifying it](https://rinkeby.etherscan.io/verifyContract) before trying again. 

Verifying it allow us/you to check the source code of the token registry via etherscan to ensure everything is in order.

For verification:
-The source code can be found (here)[https://github.com/Open-Attestation/token-registry/blob/master/contracts/ERC721.sol]
- Abi can be generated via remix ide.
- The encoded abi can be generated (here)[https://abi.hashex.org/]

**Comment by x-ajnashp** [comment]
@justussoh Thanks for the input. Issuing with new TR solved the issue.
