### ISSUE TITLE
Failing transaction when trying to use mintTitle

### ISSUE THREAD

**Issue by cargox-ks** [Open-Attestation/token-registry#131]
Hi,

## packages used
`"@govtechsg/token-registry": "^3.2.1"`

## Issue 1

I have been trying to implement transferable documents. Following the code block for minting at https://www.openattestation.com/docs/developer-section/libraries/remote-files/token-registry#minting-title-escrow my transaction gets reverted.

Token registry already exists and is deployed on goerli testnet

This is the function call:
```
      const tx = await connectedTokenRegistry.mintTitle(
        myAddress,
        myAddress,
        `0x${targetHash}`,
        {
          gasLimit: 5000000,
        }
      );
```
I want to set the document's holder and beneficiary to myself. `targetHash` is the merkle root of the wrapped documents

This is the output of the error.
```
{
  "transactionHash": "0x21677d41cb7e90cfc6124ed9f5fcd97a846986ee2220759dccc047553348a9d5",
  "transaction": {
    "hash": "0x21677d41cb7e90cfc6124ed9f5fcd97a846986ee2220759dccc047553348a9d5",
    "type": 2,
    "accessList": null,
    "blockHash": null,
    "blockNumber": null,
    "transactionIndex": null,
    "confirmations": 0,
    "from": "0x1bD64099aE5997837d298aAf849bE5b183554151",
    "gasPrice": {
      "type": "BigNumber",
      "hex": "0x1609de8caa"
    },
    "maxPriorityFeePerGas": {
      "type": "BigNumber",
      "hex": "0x59682f00"
    },
    "maxFeePerGas": {
      "type": "BigNumber",
      "hex": "0x1609de8caa"
    },
    "gasLimit": {
      "type": "BigNumber",
      "hex": "0x4c4b40"
    },
    "to": "0xFeF55bBd5Ed0F84DD5851392c91E6e2e695EBF04",
    "value": {
      "type": "BigNumber",
      "hex": "0x00"
    },
    "nonce": 52,
    "data": "0x82a96dce0000000000000000000000001bd64099ae5997837d298aaf849be5b1835541510000000000000000000000001bd64099ae5997837d298aaf849be5b183554151ca6dc196b1cee71cb2839cd89955a9caf0b13bf9bde78273ef18593d67b8c069",
    "r": "0xf0ea33c962aa67e856b021dde229498d335c7048f9f7c4fc5ba6ff950c94aa33",
    "s": "0x39c81a6f39fa0bf6a444abf17321db59e78f7b259a08bf8de35696c56229e569",
    "v": 1,
    "creates": null,
    "chainId": 0
  },
  "receipt": {
    "to": "0xFeF55bBd5Ed0F84DD5851392c91E6e2e695EBF04",
    "from": "0x1bD64099aE5997837d298aAf849bE5b183554151",
    "contractAddress": null,
    "transactionIndex": 62,
    "gasUsed": {
      "type": "BigNumber",
      "hex": "0x580b"
    },
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "blockHash": "0xda7f6dc38d8902bfcf2b1463305f59e4dc72b88e218b3c6ed56777ef1520353b",
    "transactionHash": "0x21677d41cb7e90cfc6124ed9f5fcd97a846986ee2220759dccc047553348a9d5",
    "logs": [],
    "blockNumber": 7915653,
    "confirmations": 1,
    "cumulativeGasUsed": {
      "type": "BigNumber",
      "hex": "0x60c759"
    },
    "effectiveGasPrice": {
      "type": "BigNumber",
      "hex": "0x142594a8b5"
    },
    "status": 0,
    "type": 2,
    "byzantium": true
  },
  code: CALL_EXCEPTION,
  version: providers/5.7.2
}
```

I cannot see what is wrong here.

## Issue 2

When trying to debug this issue, I was comparing the code used in **open-attestation-cli** and **token-registry**. The cli uses version `2.5.1` from **token-registry**.
What version should we use? Docs should be updated to reflect new versions.

Kind regards

**Comment by cargox-ks** [comment]
I have tried with beta version and I still get the same error as in the initial post. The transaction gets reverted on blockchain.
I can only get it to work with version 2.5.1

**Comment by superical** [comment]
Can you share a trimmed-down example repo of your code to reproduce the issue?

**Comment by cargox-ks** [comment]
```
  async function issueTransferableDocument() {
    const {
      signature: { targetHash },
    } = wrappedDocument;
    const connectedTokenRegistry = TradeTrustERC721__factory.connect(
      tokenRegistryAddress!,
      signer!
    );
    const tokenId = `0x${targetHash}`;
    const myAddress = (await signer?.getAddress()) ?? '';

    try {
      setTransactionInProgress(true);
      const tx = await connectedTokenRegistry.mint(
        myAddress,
        myAddress,
        tokenId,
        {
          gasLimit: 1000000,
        }
      );
      console.log(tx);
      const receipt = await tx.wait(1);
      console.log(receipt);
      setTxReceipt(tx.hash);
      checkDocumentIssued(wrappedDocument);
    } catch (error) {
      console.error(error);
    } finally {
      setTransactionInProgress(false);
    }
  }
```

The method looks like this.

**Comment by superical** [comment]
From the looks of your example code, it looks alright. It's difficult to tell exactly what you might be facing without more information. It seems like you are deploying the contracts yourself. Can you list down the steps you have taken from deployment to the code you have to reproduce the issue?

**Comment by cargox-ks** [comment]
That is true. We deployed the contracts ourselves on goerli.
Steps:
1. **0xFeF55bBd5Ed0F84DD5851392c91E6e2e695EBF04** <= open-attestation deploy token-registry "CargoX Test" CARGOX -n goerli -f key.txt
2. Add DNS that points to address of token registry

If we use CLI to mint the title escrow, it works fine. The problem arises when using newer versions of token registry.

**Comment by superical** [comment]
If you don’t mind, can you list down the steps _in details_ you took to deploy the contacts?

**Comment by superical** [comment]
I had another look at your mint transaction and it looks like you have used a different account from your deployer. Can you try minting with your deployer account to see how it goes?

**Comment by cargox-ks** [comment]
P
Probably you were looking at this transaction? https://goerli.etherscan.io/tx/0x8e6d84397c65af053bd949d72ad4136cdee7a3490b1faa19defe28ff33efc518
Here the deployer is wrong, but if you take a look at 
https://goerli.etherscan.io/tx/0x19fc05cc85030b9e4405b672f625dd013d2684724734544942b96a65244f3918, the deployer is supposed to be correct.

What do you mean in details? Like I said in the comment above, I used CLI to create a token registry. Then I used the code from this repo, to mint the title escrow etc.

**Comment by cargox-ks** [comment]
Hey @puayhiang.
I have tried the same procedure with new release `v4.1.0`. It produces the same error as described in the first post.

Token registry contract was created with `open-attestation-cli` which uses version `2.5.3` of token-registry.  Is this perhaps the cause?

**Comment by cargox-ks** [comment]
Thanks for the info @puayhiang 
I deployed another token registry with the `feat/token-registry-v4` version of cli. Minting the token now works.
I minted the document with owner and beneficiary set to myself. But there is a problem. When I go to https://dev.tradetrust.io/verify I have no access.

```
{"data":{"issuers":[{"name":"be1b12e2-9d64-4eb0-816e-7da552e4477b:string:CargoX","identityProof":{"type":"3d84206e-682b-434b-8eec-9b8e99064889:string:DNS-TXT","location":"9b4d786b-60c3-41f3-8710-18e2c335908d:string:sandbox.cargox.info"},"tokenRegistry":"a6381805-a015-4a78-89ff-6b2e9f670412:string:0xaB08DF29B665E0BCBBaD8838507c02A1af84cFDC"}],"$template":{"url":"74b2cb8b-580d-43d3-b4a3-cb039b214f72:string:https://generic-templates.tradetrust.io","name":"a973f91e-12c9-49cd-afc5-0b789b55d3f3:string:SIMPLE_COO","type":"ccf7d1d1-9150-4d02-a61a-342e2eab5d61:string:EMBEDDED_RENDERER"},"documentId":"dc4cba4e-14be-4e67-9f88-0d2e1c4e5679:string:Company ID","companyName":"9c811f95-9a82-45cb-be5f-b70a1fb7bcfd:string:Company name","companyAddress":"0e1b331d-79ee-4506-ac6e-8aabd8124e7a:string:Company address"},"version":"https://schema.openattestation.com/2.0/schema.json","signature":{"type":"SHA3MerkleProof","proof":[],"merkleRoot":"b5e985e0e82e8a1c54a2673c7c25e94b00a6f55ef977783d485666475de62abc","targetHash":"b5e985e0e82e8a1c54a2673c7c25e94b00a6f55ef977783d485666475de62abc"}}
```
This is an example of json for the document.

**Comment by cargox-ks** [comment]
## How to reproduce this issue
1. Create an account with metamask.
2. Use `open-attestation-cli` with version `feat/token-registry-v4`
3. Deploy token registry as documented in cli package. 
    - Our address of token registry is `0xaB08DF29B665E0BCBBaD8838507c02A1af84cFDC` and minter address is `0xEf11B42d62e3832eb0c66808C5Af2FD58b80c545`
4. Use `"@govtechsg/token-registry": "^4.1.0"` for minting
Code sample how we mint token:
```javascript
const {
    signature: { targetHash },
} = wrappedDocument;
const connectedTokenRegistry = TradeTrustToken__factory.connect(
    tokenRegistryAddress!,
    signer!
);
const tokenId = `0x${targetHash}`;
const myAddress = (await signer?.getAddress()) ?? '';

try {
    setTransactionInProgress(true);
    const gasPrice = await provider.getGasPrice();
    await connectedTokenRegistry.callStatic.mint(
        myAddress,
        myAddress,
        tokenId,
        {
            gasLimit: 2_000_000,
        }
    );
    const tx = await connectedTokenRegistry.mint(
        myAddress,
        myAddress,
        tokenId,
        {
            gasLimit: 2_000_000,
        }
    );
    console.log(tx);
    const receipt = await tx.wait(1);
    console.log(receipt);
    setTxReceipt(tx.hash);
    checkDocumentIssued(wrappedDocument);
} catch (error) {
    console.error(error);
} finally {
    setTransactionInProgress(false);
}
```

`signer` here is the same as the holder and beneficiary.

**Comment by cargox-ks** [comment]
Thanks for the advice.
I have tried updating the package, but the issue still persists. I don't have any access to the transfer functionality.

```
{"data":{"issuers":[{"name":"79ddbe11-b194-4ad8-a1df-c9f3a476698d:string:CargoX","identityProof":{"type":"436b83bb-59e7-489f-818e-35c1e2d79aef:string:DNS-TXT","location":"efdde74f-ed81-4613-9bff-f7e637615254:string:sandbox.cargox.info"},"tokenRegistry":"9e748605-e4a3-4400-9a0b-cc8aa34c6913:string:0xaB08DF29B665E0BCBBaD8838507c02A1af84cFDC"}],"$template":{"url":"d2198ab7-81a2-4558-ae07-eeaea27015c4:string:https://generic-templates.tradetrust.io","name":"90af144e-34b6-4050-8f68-dfb54139ec6b:string:SIMPLE_COO","type":"565106e8-0af2-4c2f-b4e6-c6f02be80230:string:EMBEDDED_RENDERER"},"documentId":"4b8a9164-9094-4a58-98d0-93f57b7c5ac0:string:Company ID","companyName":"31ca7d6a-e662-44bb-bf82-7acbf28d601e:string:Company name","companyAddress":"351a4eb1-fa62-47b4-851b-22200adcd7a1:string:Company address"},"version":"https://schema.openattestation.com/2.0/schema.json","signature":{"type":"SHA3MerkleProof","proof":[],"merkleRoot":"5061243047708d0bfee64c1084438a82d9eb614785000ff8aeee3694dd34af06","targetHash":"5061243047708d0bfee64c1084438a82d9eb614785000ff8aeee3694dd34af06"}}
```
Here is the document.

**Comment by cargox-ks** [comment]
@puayhiang I have tried deploying a new contract with 4.1.2.
The issue is still the same.

When I check on https://dev.tradetrust.io/viewer, I get the following error on endorsement chain:
![Screenshot 2022-12-19 at 10 58 18](https://user-images.githubusercontent.com/114581893/208399080-d434274a-30c1-4ae8-9942-fcbc97eba1e1.png)

Also in the console, there is a warning
![Screenshot 2022-12-19 at 10 59 59](https://user-images.githubusercontent.com/114581893/208399222-931af2e1-9a4a-46fd-9f67-75765d84ea0c.png)

Do you have the latest required json schema for wrapped documents?

**Comment by cargox-ks** [comment]
@puayhiang Hey. Good news. Issue solved with the new netlify site.
Thanks for the info.

Closing this issue.
