### ISSUE TITLE
Bump @govtechsg/token-registry to "^4.1.5" for nomination methods but lib throwing errors

### ISSUE THREAD

**Issue by Jorsche** [Open-Attestation/token-registry#165]
Hi all, 
 lib version used:  
"@govtechsg/open-attestation": "^6.4.0",
"@govtechsg/token-registry": "^4.1.5",
"ethers": "^5.4.7",

Was using token-registry version 2++, but nomination method not supported. 
Hence, i bumped up to 4.1.5. 
However, currently facing this issue when i build.
Appreciate ur help. 
![image](https://user-images.githubusercontent.com/26618210/229475157-69944f57-8545-4202-bd08-c86f600936ca.png)

**Comment by superical** [comment]
Can you share the steps in detail on how to reproduce your issue?

**Comment by Jorsche** [comment]
hi @superical , I was using @govtechsg/token-registry: 2.6.1 previously. 
![image](https://user-images.githubusercontent.com/26618210/229683050-3c19326b-42fb-4b92-8d26-66d94360a389.png)

However,  v2.6.1 titleEscrow.callStatic doesnt have the nominate function. Hence, I have no choice but to bump it up to v4.1.5.

The error occurs when i bump it up to v4.1.5 and after i run npm run build. 

https://user-images.githubusercontent.com/26618210/229475157-69944f57-8545-4202-bd08-c86f600936ca.png.

**Comment by superical** [comment]
I wonder if this has to do with issues in your own build. Do you have a minimal example repo to reproduce your issue?

**Comment by Jorsche** [comment]
https://github.com/Jorsche/OATokenRegistry. please take a look!

**Comment by Jorsche** [comment]
@puayhiang  thanksssssss! it workssss!!!!!!!
