### ISSUE TITLE
AccessControl error on mint function

### ISSUE THREAD

**Issue by Tim-W** [Open-Attestation/token-registry#166]
Good day, I am trying to test out the `mint()` function of the token registry. My issueDoc function is looking like this:

After successfully wrapping the document `docHash`, ...
```
const benificiary = walletAddress
const holder = walletAddress
const docHash = doc.signature.merkleRoot

console.log("Attempting to issue document " + docHash + " as the issuer " + walletAddress);
tokenRegistry.mint(benificiary, holder, "0x"+docHash).then(r => {
  console.log("Issued document at block hash: " + r.blockHash);
}).catch(e => {
  console.error(e);
});
```

However, this results in :
```
MetaMask - RPC Error: execution reverted: AccessControl: account 0x12bccd63f8755a4b297e59bb7b067a09a86fd796 is missing role 0x9f2df0fed2c77648de5860a4cc508cd0818c85b8b8a1ab4ceeef8d981c8956a6
```
followed by:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: AccessControl: account 0x12bccd63f8755a4b297e59bb7b067a09a86fd796 is missing role 0x9f2df0fed2c77648de5860a4cc508cd0818c85b8b8a1ab4ceeef8d981c8956a6"
```

Testing on the Sepolia network. The testing account: https://sepolia.etherscan.io/address/0x12bccd63f8755a4b297e59bb7b067a09a86fd796 is holding a sufficient amount of ETH to perform the transaction. What does the role hash refer to, and how would I be able to fix it? There seem to be no issues in the wrapping process beforehand.

**Comment by superical** [comment]
I see that your testing account is not the deployer nor the minter. In other to call `mint`, you need to be using an account with the minter role.
