### ISSUE TITLE
can someone guide me how can i use it using polygon testnet or mainnet?

### ISSUE THREAD

**Issue by vikasg603** [Open-Attestation/token-registry#175]
Hey, I want to mint the documents but am not able to understand how to use this library to mint the documents.

const provider = new providers.JsonRpcProvider(QUICKNODE_HTTP_ENDPOINT);
const wallet = new Wallet(metaMaskPrivateKey, provider)

const connectedRegistry = TradeTrustToken__factory.connect($someAddress,wallet);

I am trying to do something like this, But not able to understand what will be the $someAddress here.
Can someone guide me or provide me some details if I am going into the wrong direction.

**Comment by superical** [comment]
That `$someAddress` you have there should be the address to your token registry contact.

**Comment by vikasg603** [comment]
Hey @superical I still do not understand what this token registry contact is and from where to get this from?
Can you help me with the initial setup if possible?
