### ISSUE TITLE
continuous transaction failure after deploying it to polygon mainnet

### ISSUE THREAD

**Issue by vikasg603** [Open-Attestation/token-registry#177]
Hey team i deployed the contract using the command as mentioned by you
`npx hardhat deploy:token --network polygon --name "LMS" --symbol LMS`

and my contract got live on polygon mainnet "https://polygonscan.com/address/0xe9208ee654e6f90223e74aab0cfc32dae9df906d"

But whenever I am trying to mint the document, I am continuously facing "execution reverted"
Can someone help me to understand what I am doing wrong?

**Comment by superical** [comment]
Your contract in question is not a token registry contract.

**Comment by vikasg603** [comment]
Hey @superical I followed the same steps as written in the readme to deploy it.
Can you guide me how to deploy token registry contract if this one is not token registry contract

**Comment by superical** [comment]
You haven’t followed the steps. You are pointing to a completely different contract. Try again.
