### ISSUE TITLE
token-registry deploy giving errors

### ISSUE THREAD

**Issue by Zaini-Aljufry** [Open-Attestation/token-registry#6]
Hi, I'm trying to build off the IMDA tradetrust webinar 3 and run into errors when experimenting with the token-registry library. I followed the documentation and the deploy function keep giving off the error below. Am I calling it wrongly or is there a bug? Below is my code and the error from console

const {TradeTrustERC721Factory} = require('@govtechsg/token-registry')
const {ethers}= require('ethers')

const deployToken = async(hashSignature,beneficiary,holder) =>{
    try {
        const provider = ethers.getDefaultProvider("ropsten")
        const wallet = new ethers.Wallet(process.env.PRIVATE_KEY, provider)
        const factory = new TradeTrustERC721Factory(wallet);
        console.log(factory)
        const tokenRegistry = await factory.deploy("MYTOKENREGISTRY","MTR");
        console.log(tokenRegistry)
        return tokenRegistry
        // return "hi"
    } catch (error) {
        console.log(error)
    }
}
module.exports = deployToken

![image](https://user-images.githubusercontent.com/67034922/88779016-d3292500-d1bb-11ea-8d81-bd21526d41fb.png)

**Comment by Nebulis** [comment]
I think you used ethers 5 which was just released and that we don't support yet (hopefully very soon)

Try to use ethers 4

**Comment by Zaini-Aljufry** [comment]
Roger ill try that however I used ethers 5 for the document-store library and it works

**Comment by rjchow** [comment]
we're somewhat in between ethersjs versions so there's some compatibility issues because a dependency (typechain) we are using doesn't support v5 yet

**Comment by Zaini-Aljufry** [comment]
Im sorry i've change the ethers to v4.0.0 and use the steps given in the readme but its still not working below is the code i used now and the error they provide. Greatly appreciate any help you can give on this issue
![image](https://user-images.githubusercontent.com/67034922/88879280-73368b00-d25c-11ea-83d8-f2169146158f.png)

**Comment by Nebulis** [comment]
I dont see any difference with what we are doing in the CLI => https://github.com/Open-Attestation/open-attestation-cli/blob/master/src/implementations/deploy/token-registry/token-registry.ts

(here is a version before the gas parameter was added => https://github.com/Open-Attestation/open-attestation-cli/blob/f286c985974f829fb54a28f2e5be4f75c6824749/src/implementations/deploy/token-registry/token-registry.ts)

Could you create a repo with the code you are using ?

**Comment by Zaini-Aljufry** [comment]
Hi Nebulis, I've created the repo at this link https://github.com/Zaini-Aljufry/Oa-tokenregistry-test.git

ive added some comments on the utils folder file oaeth,js where the token-registry  library is being called and use. This is just a testing repo to try out the library before integrating to my main project.
thank you for the help

**Comment by Zaini-Aljufry** [comment]
Hi, i manage to solve the error for the token registry issue and will be trying out the titleescrow and see if the fix work. Currently this function will always get an args.length of 3 if i do not include a null as the last input for the deploy function. This may be something you guys can look into
![image](https://user-images.githubusercontent.com/67034922/89139548-940b2300-d571-11ea-9d02-ca14e78ab9c5.png)
![image](https://user-images.githubusercontent.com/67034922/89139580-b866ff80-d571-11ea-8c3b-2c9f78a571a2.png)

**Comment by Nebulis** [comment]
That's why we mentioned about v5 it shouldn't be a problem with V4. I didn't have time to take a look into your repo yet

**Comment by Zaini-Aljufry** [comment]
With ethers v4 the error in the repo i paste on top occurs which is the invalid response errorcode 403 export.XMLHttpRequest though

**Comment by Nebulis** [comment]
In your package-lock ethers is set to 4.0.0. If you upgrade to the latest ethers version (4.0.47) it works correctly.

I don't know why it doesn't work with 4.0.0 (probably a bug)

**Comment by Zaini-Aljufry** [comment]
Thanks Nebulis that token-registry work now, but the titleEscrow.deploy requires a titleescrowfactory address as seen below. Do i have to deploy my own titleescrowfactory contract beforehand?
![image](https://user-images.githubusercontent.com/67034922/89143363-eaca2a00-d57c-11ea-91fd-eeed3ad83847.png)

**Comment by Nebulis** [comment]
Can reuse one of those => https://github.com/Open-Attestation/open-attestation-cli/blob/master/src/implementations/deploy/title-escrow/title-escrow.ts#L11
